# Generated by Django 2.2.13 on 2021-07-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_items_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
