# Generated by Django 2.2.13 on 2021-07-28 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_items_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-name',),
            },
        ),
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.AddField(
            model_name='items',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='meta_description',
            field=models.CharField(help_text='Content for description meta tag', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='sku',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
    ]
