# Generated by Django 2.2.13 on 2021-07-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210728_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='meta_description',
            field=models.CharField(help_text='Content for description meta tag', max_length=255, null=True),
        ),
    ]
