# Generated by Django 2.2.13 on 2021-07-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210728_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='meta_description',
            field=models.CharField(default='No meta-description', help_text='Content for description meta tag', max_length=255),
            preserve_default=False,
        ),
    ]
