# Generated by Django 2.2.13 on 2021-07-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_items_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
