# Generated by Django 2.2.13 on 2021-07-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_items_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='product_content',
            field=models.TextField(blank=True),
        ),
    ]
