# Generated by Django 2.2.13 on 2021-07-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_items_product_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='categories',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='items',
            name='label',
        ),
    ]
