# Generated by Django 3.2.3 on 2021-11-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210728_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['-id']},
        ),
    ]
