# Generated by Django 3.2.3 on 2021-11-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_items_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={},
        ),
    ]
