# Generated by Django 3.2.3 on 2021-11-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'BillingAddress'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'OrderItem'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payment'},
        ),
    ]
